//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stemma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Career
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Career()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int CareerID { get; set; }
        public Nullable<bool> AttendedCollege { get; set; }
        public Nullable<bool> Graduations { get; set; }
        public Nullable<bool> HaveJob { get; set; }
        public Nullable<bool> HadJob { get; set; }
        public Nullable<bool> Accomplishments { get; set; }
        public Nullable<bool> FirstDayOfSchool { get; set; }
        public Nullable<bool> ArmedForces { get; set; }
        public Nullable<bool> Volunteer { get; set; }
        public Nullable<bool> Legacies { get; set; }
        public Nullable<bool> TechSchool { get; set; }
        public Nullable<bool> LicensesCertifications { get; set; }
        public Nullable<bool> FirstJob { get; set; }
        public Nullable<bool> WorstJob { get; set; }
        public Nullable<bool> AnythingElse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
