//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stemma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Celebration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Celebration()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int CelebrationID { get; set; }
        public Nullable<bool> HolidayRecently { get; set; }
        public Nullable<bool> PartyRecently { get; set; }
        public Nullable<bool> MilestoneRecently { get; set; }
        public Nullable<bool> CelebrateChristmas { get; set; }
        public Nullable<bool> CelebrateNYE { get; set; }
        public Nullable<bool> CelebrateThanksgiving { get; set; }
        public Nullable<bool> CelebrateValentine { get; set; }
        public Nullable<bool> CelebrateEaster { get; set; }
        public Nullable<bool> CelebrateIndependenceDay { get; set; }
        public Nullable<bool> CelebrateHalloween { get; set; }
        public Nullable<bool> CelebrateMemorialDay { get; set; }
        public Nullable<bool> CelebrateLaborDay { get; set; }
        public Nullable<bool> CelebrateMothersDay { get; set; }
        public Nullable<bool> CelebrateFathersDay { get; set; }
        public Nullable<bool> CelebrateChaunakah { get; set; }
        public Nullable<bool> CelebratePassover { get; set; }
        public Nullable<bool> CelebrateRoshHashanah { get; set; }
        public Nullable<bool> CelerateYomKippur { get; set; }
        public Nullable<bool> CelebrateRamadan { get; set; }
        public Nullable<bool> CelebrateEID { get; set; }
        public Nullable<bool> CelebrateSTPat { get; set; }
        public Nullable<bool> CelebrateBirthdays { get; set; }
        public Nullable<bool> CelebrateChineseNewYear { get; set; }
        public Nullable<bool> CelebrateQuinceanera { get; set; }
        public Nullable<bool> CelebrateBarBatMitzvah { get; set; }
        public Nullable<bool> CelebrateDayOfTheDead { get; set; }
        public Nullable<bool> CelebrateVeteransDay { get; set; }
        public Nullable<bool> CelebrateCincoDeMayo { get; set; }
        public Nullable<bool> AnythingElse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
