//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stemma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventTable()
        {
            this.Media = new HashSet<Medium>();
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int EventID { get; set; }
        public byte[] DateCreated { get; set; }
        public string EventTitle { get; set; }
        public Nullable<int> EventDay { get; set; }
        public string EventMonth { get; set; }
        public int EventYear { get; set; }
        public string PeopleInvolved { get; set; }
        public string EventCaption { get; set; }
        public string UploadMedia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medium> Media { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
