//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stemma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HobbyTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HobbyTable()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int HobbyID { get; set; }
        public Nullable<bool> PlaySports { get; set; }
        public Nullable<bool> InAShow { get; set; }
        public Nullable<bool> Travel { get; set; }
        public Nullable<bool> OutdoorPerson { get; set; }
        public Nullable<bool> TravelAbroad { get; set; }
        public Nullable<bool> Passions { get; set; }
        public Nullable<bool> Talents { get; set; }
        public Nullable<bool> Trophies { get; set; }
        public Nullable<bool> Exercise { get; set; }
        public Nullable<bool> FamilyVacation { get; set; }
        public Nullable<bool> ChildhoodVacation { get; set; }
        public Nullable<bool> AnythingElse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
