//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stemma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Memory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Memory()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int MemoryID { get; set; }
        public Nullable<bool> BrokenBones { get; set; }
        public Nullable<bool> OwnHome { get; set; }
        public Nullable<bool> DriversLicense { get; set; }
        public Nullable<bool> FirstTooth { get; set; }
        public Nullable<bool> PersonalNickName { get; set; }
        public Nullable<bool> FamilyNickName { get; set; }
        public Nullable<bool> RideBike { get; set; }
        public Nullable<bool> CommitCrime { get; set; }
        public Nullable<bool> BigMove { get; set; }
        public Nullable<bool> Vote { get; set; }
        public Nullable<bool> FamilyTraditions { get; set; }
        public Nullable<bool> EmbarrassingMoment { get; set; }
        public Nullable<bool> ProudestMoments { get; set; }
        public Nullable<bool> ChildhoodCamp { get; set; }
        public Nullable<bool> MemorializeSomeone { get; set; }
        public Nullable<bool> Concerts { get; set; }
        public Nullable<bool> FamilyPet { get; set; }
        public Nullable<bool> CurrentPet { get; set; }
        public Nullable<bool> HSDance { get; set; }
        public Nullable<bool> AnythingElse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
