//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stemma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterUser
    {
        public int RegisterUserID { get; set; }
        public int LoginID { get; set; }
        public int Email { get; set; }
    }
}
