//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stemma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Relationship()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int RelationshipsID { get; set; }
        public Nullable<bool> CurrentlyMarried { get; set; }
        public Nullable<bool> InARelationship { get; set; }
        public Nullable<bool> PreviousRomance { get; set; }
        public Nullable<bool> HaveChildren { get; set; }
        public Nullable<bool> HaveGrandchildren { get; set; }
        public Nullable<bool> OtherYoungsters { get; set; }
        public Nullable<bool> HaveParents { get; set; }
        public Nullable<bool> HaveGrandparents { get; set; }
        public Nullable<bool> OtherAdults { get; set; }
        public Nullable<bool> HaveSiblings { get; set; }
        public Nullable<bool> OtherCloseRelatives { get; set; }
        public Nullable<bool> GoodFriendships { get; set; }
        public Nullable<bool> EverythingElse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
