//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stemma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorldEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorldEvent()
        {
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public int WorldEventID { get; set; }
        public Nullable<bool> September11 { get; set; }
        public Nullable<bool> MoonLanding { get; set; }
        public Nullable<bool> NixonResigns { get; set; }
        public Nullable<bool> ElvisDies { get; set; }
        public Nullable<bool> ChallengerExplodes { get; set; }
        public Nullable<bool> WorldWar2Ends { get; set; }
        public Nullable<bool> KennedyDies { get; set; }
        public Nullable<bool> NotableElection { get; set; }
        public Nullable<bool> MLKAssassination { get; set; }
        public Nullable<bool> Y2K { get; set; }
        public Nullable<bool> BerlinWall { get; set; }
        public Nullable<bool> OJSimpsonCarChase { get; set; }
        public Nullable<bool> EndOfProhibition { get; set; }
        public Nullable<bool> AnythingElse { get; set; }
        public Nullable<bool> VietnamWar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
